services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: area_db
      POSTGRES_USER: area_user
      POSTGRES_PASSWORD: area_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - area_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U area_user -d area_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./area-backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: area_user
      DB_PASSWORD: area_password
      DB_NAME: area_db
      JWT_SECRET: your_jwt_secret_key_here
      GITHUB_CLIENT_ID: Ov23liQ7GPEEWs0hVzyM
      GITHUB_CLIENT_SECRET: d20831e34517a30903d8166a67d7aee11969be99
      GOOGLE_CLIENT_ID: 635456942993-cl4hm8rvh0pcslhjfko23cbgh18o4cdq.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      
      GOOGLE_ACCESS_TOKEN: ya29.a0AQQ_BDTLx22Fo1bcJJRlCSOUyqEYpuzKg3cy779zLanhinA6y-LWuozng7zaT4IQ0ZBXPvZjmGMsKs98TD6II-3f2lorPwLSrYV7_ZI6ReLD35i363w_7PpZ1dbRvZ2dsYdg9EchLC8IA8h2frrOyzQelVN16iQRh1DIcYCnE0unvXqAUa2Pn7S8-icJlxtFmWNV0CEaCgYKAVgSARcSFQHGX2MiL_bnS2zPqibaZLcEcicGCg0206
      GOOGLE_REFRESH_TOKEN: 1//04xGCo7l27mp1CgYIARAAGAQSNwF-L9IrjgoD_Ue0r-NnRHzTFPxOWDT4QnI1wBGLLEKMnaSQOg4pkYLtlzeVaI0a-I0_K74Bij8
      
      GOOGLE_REDIRECT_URI: http://localhost:3000/callback
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - area_network
    volumes:
      - ./area-backend/uploads:/root/uploads
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - area_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  area_network:
    driver: bridge
