FROM node:20-alpine AS builder

WORKDIR /app

COPY area_front/package*.json ./
RUN npm ci

COPY area_front/ ./
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY area_front/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
