services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: area_db
      POSTGRES_USER: area_user
      POSTGRES_PASSWORD: area_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - area_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U area_user -d area_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./area-backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: area_user
      DB_PASSWORD: area_password
      DB_NAME: area_db
      JWT_SECRET: your_jwt_secret_key_here
      GITHUB_CLIENT_ID: Ov23liQ7GPEEWs0hVzyM
      GITHUB_CLIENT_SECRET: d20831e34517a30903d8166a67d7aee11969be99
      GOOGLE_CLIENT_ID: 635456942993-cl4hm8rvh0pcslhjfko23cbgh18o4cdq.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      
      GOOGLE_ACCESS_TOKEN: ya29.a0AQQ_BDSFYXG24W0tze0mjCa9CqP2qwGU4ICPVIuJnkYXdg5-Y_qbfXXrzUGn_Fs2ldtuOhuF80u8T168s3TVbMPORnWq_jluvs-UeMXuiCpqb8LC3oi92CitV8ApWGHpuiTy2RlmV1Gp130End_nx1PfwS6ERs47Lj0aV9MhzyehNf8wQUNhQouX00MziiTpaU3klZAaCgYKATkSARcSFQHGX2Mihd-Ywjee2f7vXT6c1mWQ5g0206
      GOOGLE_REFRESH_TOKEN: 1//049IIAzsHEue6CgYIARAAGAQSNwF-L9Ir-TH4-sSQBViF3Hl1jFAvACSpFVybfphVQSnqoZ7N77eiyZbDjbR_mwtwfPr1v4SsWNA
      GOOGLE_REDIRECT_URI: http://localhost:3000/callback
      FACEBOOK_CLIENT_ID: 827003503004798
      FACEBOOK_CLIENT_SECRET: 991527f3bbb9c3a764db25e425fc7637
      FACEBOOK_REDIRECT_URI: http://localhost:3000/auth/facebook/callback
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - area_network
    volumes:
      - ./area-backend/uploads:/root/uploads
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_FACEBOOK_CLIENT_ID: 827003503004798
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - area_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  area_network:
    driver: bridge
